package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"

	"github.com/brandaogabriel7/studio-sol-backend-test-2/graph/model"
)

// Verify is the resolver for the verify field.
func (r *mutationResolver) Verify(ctx context.Context, score string) (*model.Verify, error) {
	combinations := r.Resolver.GameScoreService.GetCombinationsCount(score)
	
	return &model.Verify{Combinations: combinations}, nil
}

// Hello is the resolver for the hello field.
// This query only exists to fix an issue in retrieving the schema from the GraphQL playground.
func (r *queryResolver) Hello(ctx context.Context, name string) (string, error) {
	return fmt.Sprintf("Hello, %s", name), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
