name: Golang build and run tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build: 
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go get .

      - name: Install ginkgo CLI
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.6.1 \
          && go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.6.1 \
          && go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Build
        run: go build -v ./...

      - name: Run tests with ginkgo CLI
        run: ginkgo ./...
